### ISSUE TITLE
Rename to Quests

### ISSUE THREAD

**Issue by msteiger** [Terasology/Tasks#4]
I think that this module should be renamed back to Quests since this is what this module is about.
##

**Comment by Cervator** [comment]
Would it still be a quest if the system is reused for also sorting tasks assigned to creatures? As in, could you use a similar interface to assign things to others?

The original thought there was that Tasks would sort of be the library and Quests an example implementation that could be aimed specifically at players with some sort of interaction piece in the world to get said quests (books, floating icons, etc)

If keeping it all together makes more sense I'm fine with that :-)
