### ISSUE TITLE
Fixes for new Terasology serialization system (engine PR 3535)

### ISSUE THREAD

**Issue by Cervator** [Terasology/Tasks#7]
The new serialization system introduced by MovingBlocks/Terasology#3535 (tracking branch [`MovingBlocks/newSerialization`](https://github.com/MovingBlocks/Terasology/tree/newSerialization)) causes this module to no longer compile. 10 classes are affected and the changes seem fairly straight forward - although I'm not sure if any issues will result after.

Current users of Tasks include LightAndShadow (the NPC on the spawn platform - although I'm unsure if it still has an active quest?), ManualLabor (huh, no idea), and QuestExamples (has an example quest which is a task, so an easy test). The dependencies thus won't work either, but could be useful for testing when also fixed.

Sending this @eviltak's way as the author of the engine PR and/or to @dacharya64 in case of time availability :-)

For previous reverted fixes (may be less relevant with later changes to the serialization system), see b1576fb.

**Comment by Cervator** [comment]
Note: This is now tied to https://github.com/MovingBlocks/Terasology/issues/3490 instead - see it for details

**Comment by eviltak** [comment]
Now tracked by PR MovingBlocks/Terasology#3535.
